[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.21'
fs_permissions = [
  { access = "read", path = "./node_modules" },
  { access = "read", path = "./out" },
  { access = "read", path = "./test" }
]