name: Tests

on: workflow_dispatch

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Set output of cache
        id: yarn-cache
        run: echo "dir::$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Node dependency cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run unit tests
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: yarn test
